Web_blog_on_Django/blog/app_news/urls.py
from django.contrib.auth.decorators import permission_required
from django.urls import path

from .views import NewsListView, NewsCreateView, NewsEditView, NewsDetailView, NewsFileCreateView

app_name = 'app_news'

urlpatterns = [
    path('', NewsListView.as_view(), name='list'),
    path('create', permission_required('app_news.create_and_edit_news', login_url='create',
                                       raise_exception=True)(NewsCreateView.as_view()), name='create'),
    path('many_create', permission_required('app_news.create_and_edit_news', login_url='many_create',
                                            raise_exception=True)(NewsFileCreateView.as_view()), name='many_create'),
    path('<int:id>/edit', permission_required('app_news.create_and_edit_news', login_url='edit',
                                              raise_exception=True)(NewsEditView.as_view()), name='edit'),
    path('<int:id>', NewsDetailView.as_view(), name='detail'),
]

Web_blog_on_Django/blog/app_users/urls.py
from django.urls import path

from .views import MyLogoutView, MyLogin, RegisterUser, restore_password, UserEditView, ProfileDetailView


app_name = 'app_users'


urlpatterns = [
    path('login/', MyLogin.as_view(), name='login'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('restore_password/', restore_password, name='restore_password'),
    path('<int:id>/edit', UserEditView.as_view(), name='edit'),
    path('<int:id>', ProfileDetailView.as_view(), name='detail'),
]

Web_blog_on_Django/blog/blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('app_users.urls')),
    path('news/', include('app_news.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Web_blog_on_Django/blog/app_news/models.py
# -*- coding: utf-8 -*-

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class ImagesNews(models.Model):
    image = models.ImageField(verbose_name=_('Images'), upload_to='files/images/', blank=True)
    news = models.ForeignKey('News', null=True, default=None, blank=True, on_delete=models.CASCADE,
                             related_name='images_news', verbose_name='News')


class News(models.Model):
    active = _('active')
    not_active = _('not_active')
    STATUS_CHOICES = [
        (active, _('active')),
        (not_active, _('not_active')),
    ]
    user = models.ForeignKey(User, null=True, default=None, on_delete=models.CASCADE, blank=True,
                             related_name='user_news', verbose_name=_('User'))
    title = models.CharField(verbose_name=_('Name'), max_length=150, db_index=True, blank=True)
    content = models.CharField(verbose_name=_('Content'), max_length=1000)
    created_at = models.DateTimeField(verbose_name=_('Created at'), auto_now_add=True, blank=False)
    status = models.CharField(verbose_name=_('Status'), max_length=100, default='active', choices=STATUS_CHOICES, blank=True)
    activity = models.BooleanField(verbose_name=_('Permission to publish'), default=False, blank=True)
    tag = models.CharField(verbose_name=_('Tag'), max_length=50, default='', blank=True)
    many_news = models.FileField(verbose_name=_('File many news'), upload_to='files/file_news/', blank=True)

    class Meta:
        verbose_name = _('news')
        verbose_name_plural = _('news')
        permissions = (
            ('create_and_edit', _('create and edit')),
            ('approved', _('approved moderator'))
        )

    def __str__(self):
        return f'{self.id}. {self.title} {self.created_at}'

    def get_absolute_url(self):
        return reverse('app_news:detail', args=[self.pk])


class Comments(models.Model):
    user = models.ForeignKey(User, null=True, default=None, on_delete=models.CASCADE, blank=True,
                             related_name='user_comment', verbose_name=_('User'))
    nickname = models.CharField(max_length=50, default='', blank=True)
    text = models.CharField(verbose_name=_('Comment'), max_length=500)
    news = models.ForeignKey('News', null=True, default=None, blank=True, on_delete=models.CASCADE,
                             related_name='comments', verbose_name=_('News'))

    class Meta:
        verbose_name = _('comment')
        verbose_name_plural = _('comments')

    def __str__(self):
        return f'{self.id} {self.user} {self.text}'

Web_blog_on_Django/blog/app_news/forms.py
from django import forms

from .models import News, Comments


class NewsForm(forms.ModelForm):
    images = forms.FileField(required=False, widget=forms.ClearableFileInput(attrs={'multiple': True}))

    class Meta:
        model = News
        fields = '__all__'
        exclude = ['user', 'many_news']


class NewsFileForm(forms.ModelForm):
    many_news = forms.FileField()

    class Meta:
        model = News
        fields = ['many_news']


class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = '__all__'

Web_blog_on_Django/blog/app_news/views.py
# -*- coding: utf-8 -*-
import csv

from django.core.exceptions import PermissionDenied
from django.db.models import F
from django.shortcuts import redirect
from django.views import generic

from .forms import NewsForm, NewsFileForm, CommentsForm
from .models import News, ImagesNews


class NewsListView(generic.ListView):
    model = News
    template_name = 'app_news/news_list.html'
    context_object_name = 'news_list'

    def get_queryset(self):
        tag = F('tag')
        if 'tag' in self.request.GET:
            tag = self.request.GET['tag']
        return News.objects.filter(activity=True, tag=tag).order_by('-created_at')


class NewsFileCreateView(generic.CreateView):
    model = News
    template_name = 'app_news/news_create.html'
    form_class = NewsFileForm

    def post(self, request, *args, **kwargs):
        if not request.user.has_perm('app_news.approved_news'):
            raise PermissionDenied
        else:
            file = request.FILES['many_news']
            many_news_file = csv.reader(file.read().decode('utf-8').split('\n'))
            for row in many_news_file:
                News.objects.filter(content=row[0]).create(created_at=row[1])
            return redirect('/news')


class NewsCreateView(generic.CreateView):
    model = News
    template_name = 'app_news/news_create.html'
    form_class = NewsForm

    def post(self, request, *args, **kwargs):
        form_class = NewsForm(request.POST, request.FILES)
        if not request.user.has_perm('app_news.approved_news'):
            raise PermissionDenied
        else:
            files = request.FILES.getlist('images')
            form_class.instance.activity = True
            form_class.save()
            for file in files:
                instance = ImagesNews(news=form_class.instance, image=file)
                instance.save()
            return redirect('/news')


class NewsEditView(generic.UpdateView):
    model = News
    template_name = 'app_news/news_edit.html'
    pk_url_kwarg = 'id'
    form_class = NewsForm

    def post(self, request, *args, **kwargs):
        super().post(request, *args, **kwargs)
        form_class = NewsForm(request.POST, request.FILES)
        if not request.user.has_perm('app_news.approved_news'):
            raise PermissionDenied
        else:
            files = request.FILES.getlist('images')
            form_class.instance.activity = True
            ImagesNews.objects.filter(news=self.get_object()).delete()
            for file in files:
                ImagesNews.objects.create(news=self.get_object(), image=file)
            return redirect('/news')


class NewsDetailView(generic.DetailView):
    template_name = 'app_news/news_detail.html'
    model = News
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comment_form = CommentsForm()
        context['comment_form'] = comment_form
        context['images'] = ImagesNews.objects.filter(news=self.get_object())
        print(context['images'])
        return context

    def post(self, request, *args, **kwargs):
        comment_form = CommentsForm(request.POST)
        self.object = self.get_object()
        context = self.get_context_data(**kwargs)
        if comment_form.is_valid():
            comment_form.instance.news = self.object
            comment_form.instance.user_id = request.user.id
            comment_form.save()
        else:
            context['comment_form'] = comment_form
            context['user'] = request.user.id
        return self.render_to_response(context)

Web_blog_on_Django/blog/app_news/templates/app_news/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% block title %}{% endblock %}
</head>

<body>
    <header class="d-flex flex-md-row p-3 mb-3 border-bottom shadow-sm">
        {% if request.user.is_authenticated %}
            <h4 class="mr-md-auto font-weight-normal">{% trans "Welcome to the site" %} {{ request.user.username }}</h4>
            <a class="btn btn-outline-primary" href="{% url 'app_news:list' %}">{% trans "Home" %}</a>
            <a class="btn btn-outline-primary" href="{% url 'app_users:logout' %}">{% trans "Exit" %}</a>
            <a class="btn btn-outline-primary" href="{% url 'app_users:detail' user.profile.id %}">{% trans "My profile" %}</a>
            <a class="btn btn-outline-primary" href="{% url 'app_news:create' %}">{% trans "Create News" %}</a>
            <a class="btn btn-outline-primary" href="{% url 'app_news:many_create' %}">{% trans "Create many News" %}</a>
        {% else %}
            <a class="btn btn-outline-primary" href="{% url 'app_users:login' %}">{% trans "Enter" %} </a>
            <a class="btn btn-outline-primary" href="{% url 'app_users:register' %}">{% trans "Registration" %}</a>
        {% endif %}
    </header>
        {% block body %}{% endblock %}
</body>
</html>

Web_blog_on_Django/blog/app_news/templates/app_news/news_create.html
{% extends "app_news/base.html" %}
{% load i18n %}


{% block title %}
    <title>{% trans "Create News" %}</title>
{% endblock %}

{% block body %}
    <h2>{% trans "News" %}</h2>
    {% if request.user.is_authenticated %}
        <form method="post" enctype="multipart/form-data" >
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">{% trans "Create News" %}</button>
        </form>
    {% else %}
        <p> {% trans "Oops :(, you haven't verification" %}</p>
    {% endif %}

{% endblock %}

Web_blog_on_Django/blog/app_news/templates/app_news/news_detail.html
{% extends "app_news/base.html" %}
{% load i18n %}


{% block title %}
    <title>{{ object.title }}</title>
{% endblock %}

{% block body %}
    <h2>{{ object.title }}</h2>
    {% for img in images %}
        <p><img src="/media/{{ img.image }}" class="img-fluid" width="150" height="150" alt="картинка"></p>
    {% endfor %}
    <p> {{ object.content }} </p>
    <p>{% trans "Created at" %}: {{ object.created_at }}</p>
    <p><a href="{% url 'app_news:list' %}?tag={{ object.tag }}">{% trans "Tag" %}: {{ object.tag }}</a></p>

    <p>{% trans "Updated at" %}: {{ object.updated_at }}</p>

    <a class="btn btn-outline-primary" href="{% url 'app_news:edit' object.id%}">{% trans "Edit news" %}</a>

    <h4>{% trans "Comments" %}</h4>
    <form method="post" action="{% url 'app_news:detail' object.id %}">
        {% csrf_token %}
        {% if request.user.is_authenticated %}
            <p>{% trans "User" %}: {{ request.user }}</p>
            <p><img src="{{ user.avatar.url }}" class="img-fluid" width="50" height="50" alt="аватар"></p>
        {% else %}
            <p> {{ comment_form.nickname }} </p>
        {% endif %}
        <p> {{ comment_form.text }} </p>
        <button type="submit">{% trans "To comment on" %}</button>
    </form>

    {% for comment in object.comments.all %}
        {% if comment.user %}
            <p>{% trans "Author" %}: {{ comment.user }}</p>
        {% else %}
            <p>{% trans "Author" %}: {{ comment.nickname }}</p>
        {% endif %}
        <p>{% trans "Comment" %}: {{ comment.text }}</p> <hr>
    {% endfor %}
{% endblock %}

Web_blog_on_Django/blog/app_news/templates/app_news/news_edit.html
{% extends "app_news/base.html" %}
{% load i18n %}


{% block title %}
    <title>{% trans "Edit News" %}</title>
{% endblock %}

{% block body %}
    <h2>{% trans "Edit" %}</h2>
    <form method="post" enctype="multipart/form-data" action="{% url 'app_news:edit' object.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Edit" %}</button>
    </form>
{% endblock %}

Web_blog_on_Django/blog/app_news/templates/app_news/news_list.html
{% extends "app_news/base.html" %}
{% load i18n %}


{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block body %}
    {% if news_list %}
    <ul>
        {% for news in news_list %}
        <li>
            <a href="{% url 'app_news:detail' news.id %}">{{ news.title }}</a>
            <p><a href="">{{ news.created_at }}</a></p>
            {% comment %} <p>{% trans "Author" %}: {{ user }} {% endcomment %}
            <p>{{ news.content|truncatechars:100 }} </p>
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>{% trans "No News" %}</p>
    {% endif %}
{% endblock %}