Web_blog_on_Django/blog/app_users/urls.py
from django.urls import path

from .views import MyLogoutView, MyLogin, RegisterUser, restore_password, UserEditView, ProfileDetailView


app_name = 'app_users'


urlpatterns = [
    path('login/', MyLogin.as_view(), name='login'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('restore_password/', restore_password, name='restore_password'),
    path('<int:id>/edit', UserEditView.as_view(), name='edit'),
    path('<int:id>', ProfileDetailView.as_view(), name='detail'),
]

Web_blog_on_Django/blog/blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('app_users.urls')),
    path('news/', include('app_news.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Web_blog_on_Django/blog/app_users/models.py
# -*- coding: utf-8 -*-

from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    city = models.CharField(verbose_name=_('City'), max_length=50, blank=True, null=True)
    avatar = models.FileField(verbose_name=_('Avatar'), upload_to='files/avatars/', blank=True, null=True)

    class Meta:
        verbose_name = _('profile')
        verbose_name_plural = _('profiles')

    def __str__(self):
        return f'{self.id} {self.user} {self.city}'

Web_blog_on_Django/blog/app_users/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


class RegisterForm(UserCreationForm):
    city = forms.CharField(help_text=_('City'), max_length=50)
    avatar = forms.ImageField(help_text=_('Avatar'), required=False)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'city', 'password1', 'password2', ]


class EditRegisterForm(UserChangeForm):
    city = forms.CharField(required=False, help_text=_('City'))
    avatar = forms.FileField(required=False, help_text=_('Avatar'))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'city', 'avatar', )


class RestorePasswordForm(forms.Form):
    email = forms.EmailField()

Web_blog_on_Django/blog/app_users/views.py
# -*- coding: utf-8 -*-

from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views import generic
from django.utils.translation import gettext as _

from .models import Profile
from .forms import RegisterForm, EditRegisterForm, RestorePasswordForm


class MyLogin(LoginView):
    template_name = 'app_users/login.html'


class MyLogoutView(LogoutView):
    template_name = 'app_users/logout.html'


class RegisterUser(generic.CreateView):
    template_name = 'app_users/register.html'
    form_class = RegisterForm

    def post(self, request, *args, **kwargs):
        form_class = RegisterForm(request.POST)
        if form_class.is_valid():
            user = form_class.save()
            city = form_class.cleaned_data.get('city')
            context = {'user': user, 'city': city}
            if request.FILES.get('avatar'):
                context['avatar'] = request.FILES.get('avatar')
            Profile.objects.create(**context)
            username = form_class.cleaned_data.get('username')
            password = form_class.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
        super().post(request, *args, **kwargs)
        return redirect('app_news:list')


def restore_password(request):
    if request.method == 'POST':
        form = RestorePasswordForm(request.POST)
        if form.is_valid():
            new_password = User.objects.make_random_password()
            user_email = form.cleaned_data['email']
            current_user = User.objects.filter(email=user_email).first()
            if current_user:
                current_user.set_password(new_password)
                current_user.save()
            send_mail(
                subject=_('Password recovery'),
                message=_('Recovery'),
                from_email='admin.admin@mail.ru',
                recipient_list=[form.cleaned_data['email']]
            )
            return HttpResponse(_('Letter sent'))
    restore_password_form = RestorePasswordForm()
    context = {
        'form': restore_password_form
    }
    return render(request, 'app_users/restore_password.html', context=context)


class UserEditView(generic.UpdateView):
    model = Profile
    template_name = 'app_users/user_edit.html'
    pk_url_kwarg = 'id'
    form_class = EditRegisterForm
    success_url = '/news'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form_class = EditRegisterForm(instance=self.request.user)
        context['form_class'] = form_class
        return context

    def post(self, request, *args, **kwargs):
        user_form = EditRegisterForm(request.POST, request.FILES, instance=request.user)
        user = User.objects.get(pk=request.user.id)
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        super().post(request, *args, **kwargs)
        return super().form_valid(user_form)


class ProfileDetailView(generic.DetailView):
    template_name = 'app_users/user_detail.html'
    model = Profile
    pk_url_kwarg = 'id'

Web_blog_on_Django/blog/app_users/templates/app_users/login.html
{% extends "app_news/base.html" %}
{% load i18n %}

{% block title %}
    <title>{% trans "Login" %}</title>
{% endblock %}

{% block body %}
    <h2>{% trans "Login page" %}</h2>

    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">{% trans "Login" %}</button>
    </form>

    <p><a href="{% url 'app_users:restore_password' %}}">{% trans "Restore password" %}</a></p>
{% endblock %}

Web_blog_on_Django/blog/app_users/templates/app_users/logout.html
{% extends "app_news/base.html" %}
{% load i18n %}

{% block title %}
    <title>{% trans "Logout" %}</title>
{% endblock %}

{% block body %}
    <h2>{% trans "You success logout" %}</h2>
    <p>{% trans "Logout" %}</p>
    <a href="{% url 'app_users:login' %}">{% trans "Login again" %}</a>
{% endblock %}

Web_blog_on_Django/blog/app_users/templates/app_users/register.html
{% extends "app_news/base.html" %}
{% load i18n %}

{% block title %}
    <title>{% trans "Registration" %}</title>
{% endblock %}

{% block body %}
    <h2>{% trans "Registration" %}</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Registration" %}</button>
    </form>
{% endblock %}

Web_blog_on_Django/blog/app_users/templates/app_users/restore_password.html
{% extends "app_news/base.html" %}
{% load i18n %}

{% block title %}
    <title>{% trans "Restore password" %}</title>
{% endblock %}

{% block body %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Restore" %}</button>
    </form>
{% endblock %}

Web_blog_on_Django/blog/app_users/templates/app_users/user_detail.html
{% extends "app_news/base.html" %}
{% load i18n %}


{% block title %}
    <title>{{ object.id }}</title>
{% endblock %}

{% block body %}
    {% csrf_token %}
    <h2> {% trans "Nickname" %} - {{ user.username }}</h2>
    <p> {% trans "Name" %} - {{ user.first_name }} </p>
    <p> {% trans "Surname" %} - {{ user.last_name }} </p>
    <p> {% trans "City" %} - {{ object.city }} </p> <br>
    <p><img src="{{ object.avatar.url }}" class="img-fluid" width="150" height="150" alt="{% trans 'avatar' %}"></p>

    <a class="btn btn-outline-primary" href="{% url 'app_users:edit' object.id%}">{% trans "Edit Profile" %}</a>
{% endblock %}

Web_blog_on_Django/blog/app_users/templates/app_users/user_edit.html
{% extends "app_news/base.html" %}
{% load i18n %}


{% block title %}
    <title>{% trans "Edit Profile" %}</title>
{% endblock %}

{% block body %}
    <h2>{% trans "Edit Profile" %}</h2>
    <form method="post" enctype="multipart/form-data" action="{% url 'app_users:edit' user.profile.id %}">
        {% csrf_token %}
        <p>{% trans "Name" %}: {{ form_class.first_name }}</p>
        <p>{% trans "Surname" %}: {{ form_class.last_name }}</p>
        <p>{% trans "City" %}: {{ form.city }}</p>
        <p>{% trans "Avatar" %}: {{ form.avatar }}</p>
        <button type="submit">{% trans "Edit" %}</button>
    </form>
{% endblock %}